# Generated by Django 5.2.3 on 2025-06-20 08:11

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
